### ISSUE TITLE
Add rustdoc feature labels

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/itermore#6]
Add the following to Cargo.toml

```toml
[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
```

Add the nightly feature to the crate root

```
#![cfg_attr(docsrs, feature(doc_cfg))]
```

Then add an attribute like this to public items

```rust
#[cfg_attr(docsrs, doc(cfg(feature = "array_chunks")))]
```

Test using

```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --open
```
